[colors.cursor]
cursor = "0xC0CAF5"
text = "0x1A1B26"

[colors.primary]
background = "0x1A1B26"
foreground = "0xC0CAF5"

[cursor]
blink = true
style = "Block"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true

[window.padding]
x = 8
y = 8
